### ISSUE TITLE
저장소 이름 변경 부탁드립니다.

### ISSUE THREAD

**Issue by sigmadream** [SupWhale/ks-web#1]
Web-Programming-Report  에서 ks-web 으로 변경부탁드립니다.

**Comment by SupWhale** [comment]
> Web-Programming-Report 에서 ks-web 으로 변경부탁드립니다.

레파지토리 이름을 교수님이 말씀하신대로 변경하였습니다. 확인 부탁드립니다.

**Comment by sigmadream** [comment]
감사합니다. 

즐거운 주말 되세요!
